import { Startup, Investor, EcosystemEvent, Job } from './types';

export const STARTUPS: Startup[] = [
  { name:"Darwinbox", founder:"Chaitanya Peddi, Jayant Paleti, Rohit Chennamaneni, Vineet Singh", category:"SaaS", stage:"Unicorn", funding:"$307M", founded:2015, location:"Banjara Hills, Hyderabad", desc:"End-to-end cloud HR platform unifying recruitment, onboarding, payroll and performance for 350+ global enterprises. Hyderabad's only unicorn valued at $1B+.", color:"#7c6af7", initials:"DB", website:"https://darwinbox.com" },
  { name:"Keka HR", founder:"Vijay Yalamanchili", category:"SaaS", stage:"Series A", funding:"$57M", founded:2015, location:"Jubilee Hills, Hyderabad", desc:"Cloud-based HR & payroll automation platform for mid-sized enterprises. India's fastest-growing HR SaaS — raised $57M Series A in 2024.", color:"#1dd5a0", initials:"KH", website:"https://keka.com" },
  { name:"Skyroot Aerospace", founder:"Pawan Kumar Chandana, Naga Bharath Daka", category:"SpaceTech", stage:"Series C", funding:"$95.1M", founded:2018, location:"Gachibowli, Hyderabad", desc:"India's first privately developed orbital launch vehicle company. The Vikram series rockets make small-satellite deployment affordable and accessible.", color:"#5ba4f5", initials:"SA", website:"https://skyroot.in" },
  { name:"Dhruva Space", founder:"Sanjay Nekkanti", category:"SpaceTech", stage:"Series A", funding:"$40M", founded:2012, location:"HITEC City, Hyderabad", desc:"End-to-end space technology solutions provider. Launched India's first commercial satellite mission aboard SpaceX in 2025 — a historic milestone.", color:"#5ba4f5", initials:"DS", website:"https://dhruvaspace.com" },
  { name:"Fourth Partner Energy", founder:"Vivek Subramanian, Saif Dhorajiwala", category:"CleanTech", stage:"Series D", funding:"$710M+", founded:2010, location:"Financial District, Hyderabad", desc:"India's largest commercial and industrial solar energy company. Operates utility-scale, rooftop and open-access solar projects across 15+ states.", color:"#f5a623", initials:"FP", website:"https://fourthpartner.co" },
  { name:"StanPlus", founder:"Prabhdeep Singh, Tanmay Newatia", category:"Health", stage:"Series B", funding:"$30M", founded:2015, location:"Madhapur, Hyderabad", desc:"Tech-enabled 24/7 emergency medical transportation using GPS tracking and optimised hospital dispatch. Building India's most reliable emergency network.", color:"#ff6b6b", initials:"SP", website:"https://stanplus.com" },
  { name:"Credright", founder:"Neeraj Bansal, Vineet Jawa", category:"FinTech", stage:"Series B", funding:"$23.5M", founded:2016, location:"Banjara Hills, Hyderabad", desc:"Fintech lending platform bridging the credit gap for micro and small businesses underserved by traditional banking with streamlined digital workflows.", color:"#e879b0", initials:"CR", website:"https://credright.com" },
  { name:"NextBillion.ai", founder:"Ajay Bulusu, Gaurav Bubna", category:"AI", stage:"Series B", funding:"$45M", founded:2018, location:"HITEC City, Hyderabad", desc:"AI-powered mapping and navigation APIs purpose-built for emerging markets. Their customisable location stack powers logistics, mobility and last-mile delivery.", color:"#7c6af7", initials:"NB", website:"https://nextbillion.ai" },
  { name:"Marut Drones", founder:"Prem Kumar Vislawath", category:"AgriTech", stage:"Series B", funding:"$18M", founded:2019, location:"HITEC City, Hyderabad", desc:"India's leading agri-drone company offering precision spraying, seeding and crop-monitoring services. Deep-tech meets farm productivity.", color:"#5ecb8a", initials:"MD", website:"https://marutdrones.com" },
  { name:"Kenyt.AI", founder:"Ravi Saini", category:"AI", stage:"Series A", funding:"$5M", founded:2018, location:"Gachibowli, Hyderabad", desc:"Multilingual chatbots and voicebots for enterprise customer engagement across WhatsApp, web and phone in 30+ Indian languages.", color:"#a08bff", initials:"KA", website:"https://kenyt.ai" },
  { name:"Wehouse", founder:"Sripad Nandiraj", category:"SaaS", stage:"Series A", funding:"$3.8M", founded:2017, location:"Gachibowli, Hyderabad", desc:"Technology platform streamlining home construction from design to final handover — single-window access to architects, contractors and materials.", color:"#1dd5a0", initials:"WH", website:"https://wehouse.in" },
  { name:"Hala Mobility", founder:"Abhinav Kumar", category:"CleanTech", stage:"Series A", funding:"$12M", founded:2020, location:"HITEC City, Hyderabad", desc:"Tech-enabled EV rental and subscription services accelerating Hyderabad's shift to electric mobility with flexible ownership for individuals and fleets.", color:"#5ecb8a", initials:"HM", website:"https://halamobility.com" },
  { name:"EON Space Labs", founder:"Amrutha Jolly", category:"SpaceTech", stage:"Seed", funding:"$1.2M", founded:2022, location:"T-Hub, Hyderabad", desc:"T-Hub incubated deep-tech startup building India's lightest high-resolution space telescope with miniaturised optics for Earth observation missions.", color:"#5ba4f5", initials:"ES", website:"https://eonspacelabs.com" },
  { name:"Cosmoserve Space", founder:"Rohan Murthy", category:"SpaceTech", stage:"Pre-Seed", funding:"$3.2M", founded:2025, location:"T-Hub, Hyderabad", desc:"Developing autonomous robotic spacecraft to remove orbital debris — tackling one of the biggest threats to satellite operations and future spaceflight.", color:"#5ba4f5", initials:"CS", website:"https://cosmoservespace.com" },
  { name:"Narra.AI", founder:"Vivek Sharma", category:"AI", stage:"Seed", funding:"$3M", founded:2023, location:"Madhapur, Hyderabad", desc:"AI-powered content intelligence platform for brands and media companies. Automates content workflows and delivers deep audience insights at scale.", color:"#7c6af7", initials:"NA", website:"https://narra.ai" },
  { name:"UrbanKissan", founder:"Narayanan Ayyappan", category:"AgriTech", stage:"Series A", funding:"$8M", founded:2018, location:"Secunderabad, Hyderabad", desc:"Sustainable urban farming platform connecting consumers directly with local organic farmers, cutting food miles and ensuring farm-fresh produce delivery.", color:"#5ecb8a", initials:"UK", website:"https://urbankissan.com" }
];

export const INVESTORS: Investor[] = [
  { name:"Peak XV Partners", type:"Venture Capital", focus:"SaaS, FinTech, Consumer Tech — Series A to D", portfolio:"Darwinbox, Keka HR, 80+ Hyd companies", initials:"PX", color:"#7c6af7" },
  { name:"T-Hub Foundation", type:"Incubator / Accelerator", focus:"All sectors — world's largest startup incubator", portfolio:"EON Space Labs, Kenyt.AI, 2,000+ startups", initials:"TH", color:"#1dd5a0" },
  { name:"Accel India", type:"Venture Capital", focus:"Early-stage SaaS, Consumer & Deep Tech", portfolio:"Skyroot, Keka HR, Darwinbox, 50+ portfolio", initials:"AC", color:"#5ba4f5" },
  { name:"WE-Hub", type:"Women Entrepreneur Hub", focus:"Women-led startups across all sectors", portfolio:"150+ women founders mentored & funded", initials:"WH", color:"#e879b0" },
  { name:"CIE IIIT Hyderabad", type:"University Incubator", focus:"Deep Tech, AI, Enterprise & Cybersecurity", portfolio:"NextBillion.ai, 100+ alumni startups", initials:"CI", color:"#f5a623" },
  { name:"Temasek Holdings", type:"Sovereign Wealth Fund", focus:"Growth & late-stage technology companies", portfolio:"Skyroot Aerospace, multiple Hyd investments", initials:"TM", color:"#5ecb8a" },
  { name:"Tiger Global Management", type:"Global Venture Capital", focus:"SaaS, FinTech, Consumer Internet", portfolio:"Multiple Hyderabad portfolio companies", initials:"TG", color:"#ff6b6b" },
  { name:"Anthill Ventures", type:"Angel Network & Micro-VC", focus:"Seed to Series A — B2B SaaS & Deep Tech", portfolio:"Wehouse, UrbanKissan, 30+ startups", initials:"AV", color:"#7c6af7" }
];

export const EVENTS: EcosystemEvent[] = [
  { day:"19", month:"Apr", title:"Founder Friday — Pitch Night #48", venue:"T-Hub Phase 2, Raidurgam, Hyderabad", type:"Pitch Night", typeColor:"#7c6af7", desc:"Monthly pitch competition open to early-stage Hyd startups. 5-min pitches, investor feedback, networking." },
  { day:"26", month:"Apr", title:"Deep Tech Demo Day — SpaceTech Edition 2026", venue:"IIIT Hyderabad Auditorium, Gachibowli", type:"Demo Day", typeColor:"#5ba4f5", desc:"Showcasing Hyderabad's top spacetech startups including Skyroot, Dhruva Space, EON Space Labs and Cosmoserve." },
  { day:"3", month:"May", title:"HydTech Hackathon 2026 — AI & Sustainability", venue:"Microsoft Hyderabad Campus, Gachibowli", type:"Hackathon", typeColor:"#1dd5a0", desc:"48-hour hackathon focused on AI solutions for climate change. ₹10L+ in prizes. Open to student and pro teams." },
  { day:"10", month:"May", title:"WE-Hub Women Founders Summit 2026", venue:"WE-Hub, IIIT-H Campus, Hyderabad", type:"Summit", typeColor:"#e879b0", desc:"Annual summit celebrating women entrepreneurs in Telangana. Fireside chats, investor meets, mentorship sessions." },
  { day:"17", month:"May", title:"ET Soonicorns Sundowner — Hyderabad Chapter", venue:"Park Hyatt Hyderabad, Banjara Hills", type:"Networking", typeColor:"#f5a623", desc:"Exclusive evening networking event connecting Hyderabad's top founders and investors. Invite-only, 150 attendees." },
  { day:"24", month:"May", title:"AgriTech & DronesTech Innovation Conclave", venue:"ICRISAT Campus, Patancheru, Hyderabad", type:"Conference", typeColor:"#5ecb8a", desc:"Full-day conference on precision agriculture, drone technology and agri-fintech. Features Marut Drones, UrbanKissan and more." },
  { day:"7", month:"Jun", title:"GITEX Hyderabad Startup Boulevard 2026", venue:"Hyderabad International Convention Centre", type:"Expo", typeColor:"#ff6b6b", desc:"Regional edition of GITEX featuring 200+ Hyderabad startups. International investor delegations, live demos and pitching stages." }
];

export const JOBS: Job[] = [
  { id:1, title:"Senior Backend Engineer", company:"Darwinbox", initials:"DB", color:"#7c6af7", category:"Engineering", location:"Banjara Hills, Hyd", type:"Full-Time", salary:"₹28L–₹45L", exp:"4–7 yrs", desc:"Build and scale microservices powering HR workflows for 350+ global enterprises. Strong Node.js, PostgreSQL and AWS skills required." },
  { id:2, title:"ML Engineer — NLP", company:"Kenyt.AI", initials:"KA", color:"#a08bff", category:"Data", location:"Gachibowli, Hyd", type:"Full-Time", salary:"₹18L–₹32L", exp:"2–5 yrs", desc:"Train and deploy multilingual NLP models for conversational AI in 30+ Indian languages. Experience with transformers and LLM fine-tuning a plus." },
  { id:3, title:"Product Manager — Growth", company:"Keka HR", initials:"KH", color:"#1dd5a0", category:"Product", location:"Jubilee Hills, Hyd", type:"Full-Time", salary:"₹22L–₹38L", exp:"3–6 yrs", desc:"Own the growth product roadmap for India's fastest-growing HR SaaS. Drive activation, retention and expansion metrics across 7,000+ SME customers." },
  { id:4, title:"Aerospace Systems Engineer", company:"Skyroot Aerospace", initials:"SA", color:"#5ba4f5", category:"Engineering", location:"Gachibowli, Hyd", type:"Full-Time", salary:"₹20L–₹36L", exp:"3–6 yrs", desc:"Design and test propulsion and avionics systems for the Vikram launch vehicle series. Experience in MATLAB, systems integration and launch ops preferred." },
  { id:5, title:"UI/UX Designer", company:"NextBillion.ai", initials:"NB", color:"#7c6af7", category:"Design", location:"HITEC City, Hyd", type:"Full-Time", salary:"₹14L–₹24L", exp:"2–4 yrs", desc:"Design intuitive dashboards and developer portals for AI-powered mapping APIs used across 25+ countries. Figma and user research expertise required." },
  { id:6, title:"Drone Operations Lead", company:"Marut Drones", initials:"MD", color:"#5ecb8a", category:"Operations", location:"HITEC City, Hyd", type:"Full-Time", salary:"₹10L–₹18L", exp:"2–4 yrs", desc:"Manage end-to-end agri-drone spraying operations across Telangana and AP. DGCA drone pilot certification required." },
  { id:7, title:"Sales Development Rep", company:"Wehouse", initials:"WH", color:"#1dd5a0", category:"Sales", location:"Gachibowli, Hyd", type:"Full-Time", salary:"₹8L–₹14L", exp:"1–3 yrs", desc:"Drive inbound and outbound pipeline for Wehouse's home construction SaaS. Excellent Telugu and Hindi communication. B2C real-estate background preferred." },
  { id:8, title:"Data Scientist — Solar Forecasting", company:"Fourth Partner Energy", initials:"FP", color:"#f5a623", category:"Data", location:"Financial District, Hyd", type:"Full-Time", salary:"₹16L–₹28L", exp:"2–5 yrs", desc:"Build ML models predicting solar generation, grid demand and energy pricing for India's largest C&I solar operator. Python, time-series and GIS skills a must." },
  { id:9, title:"Android Engineer", company:"StanPlus", initials:"SP", color:"#ff6b6b", category:"Engineering", location:"Madhapur, Hyd", type:"Full-Time", salary:"₹14L–₹22L", exp:"2–4 yrs", desc:"Build the StanPlus driver and dispatch apps used by 1,000+ emergency response teams. Kotlin, maps SDK and real-time Firebase experience required." },
  { id:10, title:"FinTech Credit Analyst", company:"Credright", initials:"CR", color:"#e879b0", category:"Operations", location:"Banjara Hills, Hyd", type:"Full-Time", salary:"₹9L–₹16L", exp:"1–3 yrs", desc:"Evaluate MSE loan applications using alternative data models. CFA or MBA Finance preferred. Strong Excel and credit underwriting background." },
  { id:11, title:"DevOps / Platform Engineer", company:"Darwinbox", initials:"DB", color:"#7c6af7", category:"Engineering", location:"Hybrid — Hyderabad", type:"Hybrid", salary:"₹22L–₹38L", exp:"3–6 yrs", desc:"Own the Kubernetes infrastructure serving 2M+ daily active users. Expertise in Terraform, Helm, Prometheus and multi-cloud deployments (AWS + GCP)." },
  { id:12, title:"Content & Growth Intern", company:"Narra.AI", initials:"NA", color:"#a08bff", category:"Sales", location:"Madhapur, Hyd", type:"Internship", salary:"₹20K–₹30K/mo", exp:"Fresher", desc:"Create compelling B2B content and manage social channels for an AI content-intelligence startup. Strong English writing and social media instincts required." },
  { id:13, title:"Satellite Mission Analyst", company:"Dhruva Space", initials:"DS", color:"#5ba4f5", category:"Engineering", location:"HITEC City, Hyd", type:"Full-Time", salary:"₹18L–₹30L", exp:"2–5 yrs", desc:"Support mission planning, orbit determination and satellite health monitoring for active LEO constellations. STK and Python scripting skills preferred." },
  { id:14, title:"EV Fleet Operations Manager", company:"Hala Mobility", initials:"HM", color:"#5ecb8a", category:"Operations", location:"HITEC City, Hyd", type:"Full-Time", salary:"₹12L–₹20L", exp:"3–5 yrs", desc:"Manage Hala's growing EV fleet of 1,000+ scooters across Hyderabad. Oversee charging ops, driver onboarding, and last-mile performance metrics." },
  { id:15, title:"Full-Stack Engineer (React + Node)", company:"UrbanKissan", initials:"UK", color:"#5ecb8a", category:"Engineering", location:"Secunderabad, Hyd", type:"Full-Time", salary:"₹12L–₹20L", exp:"2–4 yrs", desc:"Build the consumer marketplace and farmer-facing supply platform for sustainable urban produce delivery. TypeScript, Next.js and MongoDB stack." },
  { id:16, title:"Product Designer — Mobile", company:"StanPlus", initials:"SP", color:"#ff6b6b", category:"Design", location:"Remote / Hyderabad", type:"Remote", salary:"₹14L–₹22L", exp:"2–4 yrs", desc:"Design life-saving UX for emergency dispatch and patient-tracking apps. Strong mobile design systems, accessibility and rapid prototyping skills." }
];
